import 'server-only'
import { randomUUID } from 'crypto'
import { mkdir, readFile, rm, writeFile } from 'fs/promises'
import path from 'path'

// Deliberately outside `public/` — Next only serves that directory over HTTP
// by default, so this is only reachable through the authenticated
// /api/admin/quotes/[id]/image route.
const UPLOADS_DIR =
  process.env.QUOTE_UPLOADS_DIR ||
  path.join(/* turbopackIgnore: true */ process.cwd(), 'uploads', 'quote-images')

const EXTENSIONS: Record<string, string> = {
  'image/png': 'png',
  'image/jpeg': 'jpg',
  'image/gif': 'gif',
  'image/webp': 'webp',
}

// Filenames are always generated by saveQuoteImage(), never taken from user
// input, but this guards against that invariant ever being broken.
function resolveSafePath(filename: string) {
  const resolved = path.join(UPLOADS_DIR, filename)
  if (path.dirname(resolved) !== UPLOADS_DIR) {
    throw new Error('Invalid image filename.')
  }
  return resolved
}

export async function saveQuoteImage(buffer: Buffer, contentType: string): Promise<string> {
  const extension = EXTENSIONS[contentType] ?? 'bin'
  const filename = `${randomUUID()}.${extension}`

  await mkdir(UPLOADS_DIR, { recursive: true })
  await writeFile(resolveSafePath(filename), buffer)

  return filename
}

export async function readQuoteImage(filename: string): Promise<Buffer> {
  return readFile(resolveSafePath(filename))
}

export async function deleteQuoteImage(filename: string): Promise<void> {
  try {
    await rm(resolveSafePath(filename))
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code !== 'ENOENT') throw err
  }
}
